spring.application.name=toko-olahraga-v2

# 1. Pengaturan Koneksi ke MySQL phpMyAdmin
spring.datasource.url=jdbc:mysql://localhost:3306/pbo2_toko_olahraga?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Pengaturan Hibernat / JPA (Penerjemah SQL Otomatis)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Biar kita bisa ngintip query SQL yang dibuat Spring Boot di console/terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true